[package]
name = "zed_jai"
version = "0.0.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/jai.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.0.6"
