name = "Jai"
grammar = "jai"
path_suffixes = ["jai"]
# autoclose_before = ",=)}]"
line_comments = ["//"]
block_comment = ["/*", "*/"]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = false },
    { start = "(", end = ")", close = true, newline = false },
    { start = "'", end = "'", close = true, newline = false },
    { start = "/*", end = "*/", close = true, newline = false },
    { start = "\"", end = "\"", close = true, newline = false },
]
